services:
  postgres_sae_tt:
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esferico_sae_tt_db
    ports:
      - "55432:5432"
    volumes:
      - pgdata_sae_tt:/var/lib/postgresql

  postgres_sae_tt_tests:
    image: postgis/postgis:18-3.6
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: esferico_sae_tt_tests_db
    ports:
      - "55433:5432"
    volumes:
      - pgdata_sae_tt_tests:/var/lib/postgresql

volumes:
  pgdata_sae_tt:
  pgdata_sae_tt_tests: